// <auto-generated/>
// Polyfills required for netstandard2.0 targets that use C# 9+ language features.

// record types need IsExternalInit, which does not exist in netstandard2.0.
namespace System.Runtime.CompilerServices
{
    internal static class IsExternalInit { }
}
